name: running-ci

# Run this workflow whenever code is pushed to the repo
on: push

jobs:
  test:
    # Use a clean Ubuntu machine provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code onto the machine
      - uses: actions/checkout@v4
      
      # Step 2: Install Python on the machine      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install your dependencies          
      - run: pip install .[test]

      # Step 4: Run your tests      
      - run: pytest